global using HotelWise.Core.SDK.Abstractions;
global using HotelWise.Core.SDK.Common;
global using HotelWise.Core.SDK.Common.Constants;
global using HotelWise.Core.SDK.Domain;
global using HotelWise.Core.SDK.Extensions;
global using HotelWise.Core.SDK.Infrastructure;
global using HotelWise.Core.SDK.Helpers;
global using HotelWise.Core.SDK.Security;
global using HotelWise.Core.SDK.AI.DTO;
