global using SmartCoreHub.Core.SDK.Domain.DTOs.Common;
global using EntityTypeConfigurationConstants = SmartCoreHub.Core.SDK.Common.Constants.EntityTypeConfigurationConstants;
global using ETypeDataBase = SmartCoreHub.Core.SDK.Common.ETypeDataBase;
global using SmartCoreHub.Core.SDK.Domain.Entities.Common;
global using SmartCoreHub.Core.SDK.EntityFrameworkCore.Repositories;
global using SmartCoreHub.Core.SDK.Infrastructure.Repositories.Generic;
global using SmartCoreHub.Core.SDK.Domain.Interfaces.Common;
global using SmartCoreHub.Core.SDK.Domain.AI.DTO;
global using SmartCoreHub.Core.SDK.Domain.Helpers;
global using SmartCoreHub.Core.SDK.Infrastructure.Data;
