global using SmartCoreHub.Core.SDK.Domain.Abstractions;
global using SmartCoreHub.Core.SDK.Common;
global using SmartCoreHub.Core.SDK.Common.Constants;
global using SmartCoreHub.Core.SDK.Common.Security;
global using SmartCoreHub.Core.SDK.Domain.Helpers;
global using SmartCoreHub.Core.SDK.Service.API.Helpers.Ported;
global using SmartCoreHub.Core.SDK.Domain.AI.DTO;
global using SmartCoreHub.Core.SDK.Domain.AI.Abstractions;
global using SmartCoreHub.Core.SDK.Domain.AI.Configuration;
