<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>CS8604,CS8600,CS8602,CS1998,CS8618,CS8601,CS8629,CS0618,SKEXP0050,SKEXP0001,SKEXP0010,SKEXP0070,SKEXP0110,HW_CORE_SDK_DOMAIN,HW_CORE_SDK_REPO,HW_CORE_SDK_COMMON,HW_CORE_SDK_SERVICE,HW_CORE_SDK_HELPER,HW_CORE_SDK_SECURITY,HW_CORE_SDK_AI,HW_CORE_SDK_MIDDLEWARE,HW_CORE_SDK_DI,HW_CORE_SDK_LOGGING</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="Azure.Data.Tables" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="DocumentFormat.OpenXml.Framework" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
    <PackageReference Include="Microsoft.Extensions.VectorData.Abstractions" />
    <PackageReference Include="Microsoft.Identity.Web" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="CommunityToolkit.VectorData.InMemory" />
    <PackageReference Include="CommunityToolkit.VectorData.Qdrant" />
    <PackageReference Include="Microsoft.SemanticKernel" />
    <PackageReference Include="Microsoft.SemanticKernel.Abstractions" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Abstractions" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Core" />
    <PackageReference Include="Microsoft.SemanticKernel.Core" />
    <PackageReference Include="Microsoft.SemanticKernel.Plugins.Memory" />
    <PackageReference Include="Microsoft.SemanticKernel.PromptTemplates.Handlebars" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Mistral.SDK" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="OllamaSharp" />
    <PackageReference Include="PDFsharp" />
    <PackageReference Include="PDFsharp-MigraDoc" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Polly.Core" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" />
    <PackageReference Include="System.IO.Packaging" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GroqApiLibrary\GroqApiLibrary.csproj" />
    <ProjectReference Include="..\HotelWise.Core.SDK\HotelWise.Core.SDK.csproj" />
  </ItemGroup>
</Project>